import androidx.compose.material.icons.materialPath
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.unit.dp

@Suppress("BooleanLiteralArgument")
object CustomIcons {

    val ConvertVector =
        ImageVector.Builder("ConvertVector", 24.dp, 24.dp, 24F, 24F)
            .materialPath {
                moveTo(2F, 3F)
                verticalLineTo(9F)
                horizontalLineTo(4.95F)
                lineTo(6.95F, 15F)
                horizontalLineTo(6F)
                verticalLineTo(21F)
                horizontalLineTo(12F)
                verticalLineTo(16.41F)
                lineTo(17.41F, 11F)
                horizontalLineTo(22F)
                verticalLineTo(5F)
                horizontalLineTo(16F)
                verticalLineTo(9.57F)
                lineTo(10.59F, 15F)
                horizontalLineTo(9.06F)
                lineTo(7.06F, 9F)
                horizontalLineTo(8F)
                verticalLineTo(3F)
                moveTo(4F, 5F)
                horizontalLineTo(6F)
                verticalLineTo(7F)
                horizontalLineTo(4F)
                moveTo(18F, 7F)
                horizontalLineTo(20F)
                verticalLineTo(9F)
                horizontalLineTo(18F)
                moveTo(8F, 17F)
                horizontalLineTo(10F)
                verticalLineTo(19F)
                horizontalLineTo(8F)
                close()
                moveTo(19F, 21F)
                verticalLineTo(19F)
                horizontalLineTo(15F)
                verticalLineTo(17F)
                horizontalLineTo(19F)
                verticalLineTo(15F)
                lineTo(22F, 18F)
                lineTo(19F, 21F)
            }.build()

    val DestinationDirectory =
        ImageVector.Builder("DestinationDirectory", 24.dp, 24.dp, 24F, 24F)
            .materialPath {
                moveTo(20F, 18F)
                horizontalLineTo(4F)
                verticalLineTo(8F)
                horizontalLineTo(20F)
                moveTo(20F, 6F)
                horizontalLineTo(12F)
                lineTo(10F, 4F)
                horizontalLineTo(4F)
                arcTo(2F, 2F, 0F, false, false, 2F, 6F)
                verticalLineTo(18F)
                arcTo(2F, 2F, 0F, false, false, 4F, 20F)
                horizontalLineTo(20F)
                arcTo(2F, 2F, 0F, false, false, 22F, 18F)
                verticalLineTo(8F)
                arcTo(2F, 2F, 0F, false, false, 20F, 6F)
                moveTo(14F, 9F)
                horizontalLineTo(16F)
                verticalLineTo(13F)
                horizontalLineTo(19F)
                lineTo(15F, 17F)
                lineTo(11F, 13F)
                horizontalLineTo(14F)
                close()
            }.build()

    val ExploreFiles =
        ImageVector.Builder("ExploreFiles", 24.dp, 24.dp, 24F, 24F)
            .materialPath {
                moveTo(4F, 4F)
                curveTo(2.89F, 4F, 2F, 4.89F, 2F, 6F)
                verticalLineTo(18F)
                arcTo(2F, 2F, 0F, false, false, 4F, 20F)
                horizontalLineTo(20F)
                arcTo(2F, 2F, 0F, false, false, 22F, 18F)
                verticalLineTo(8F)
                curveTo(22F, 6.89F, 21.1F, 6F, 20F, 6F)
                horizontalLineTo(12F)
                lineTo(10F, 4F)
                horizontalLineTo(4F)
                moveTo(4F, 8F)
                horizontalLineTo(20F)
                verticalLineTo(18F)
                horizontalLineTo(4F)
                verticalLineTo(8F)
                moveTo(7F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(9F)
                verticalLineTo(22F)
                horizontalLineTo(7F)
                moveTo(11F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(13F)
                verticalLineTo(22F)
                horizontalLineTo(11F)
                moveTo(15F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(17F)
                verticalLineTo(22F)
                horizontalLineTo(15F)
            }.build()

    val SourceFiles =
        ImageVector.Builder("SourceFiles", 24.dp, 24.dp, 24F, 24F)
            .materialPath {
                // M12,12L16,16H13.5V19H10.5V16H8L12,12Z
                moveTo(16F, 0F)
                horizontalLineTo(8F)
                curveTo(6.9F, 0F, 6F, .9F, 6F, 2F)
                verticalLineTo(18F)
                curveTo(6F, 19.1F, 6.9F, 20F, 8F, 20F)
                horizontalLineTo(20F)
                curveTo(21.1F, 20F, 22F, 19.1F, 22F, 18F)
                verticalLineTo(6F)
                lineTo(16F, 0F)
                moveTo(20F, 18F)
                horizontalLineTo(8F)
                verticalLineTo(2F)
                horizontalLineTo(15F)
                verticalLineTo(7F)
                horizontalLineTo(20F)
                verticalLineTo(18F)
                moveTo(4F, 4F)
                verticalLineTo(22F)
                horizontalLineTo(20F)
                verticalLineTo(24F)
                horizontalLineTo(4F)
                curveTo(2.9F, 24F, 2F, 23.1F, 2F, 22F)
                verticalLineTo(4F)
                horizontalLineTo(4F)
                close()
                moveTo(14F, 8F)
                lineTo(18F, 12F)
                horizontalLineTo(15F)
                verticalLineTo(16F)
                horizontalLineTo(13F)
                verticalLineTo(12F)
                horizontalLineTo(10F)
                lineTo(14F, 8F)
                close()
            }.build()
}
