package com.amarland.svg2iv.ui

import androidx.compose.material.icons.materialIcon
import androidx.compose.material.icons.materialPath

@Suppress("BooleanLiteralArgument")
object CustomIcons {

    val ConvertVector =
        materialIcon("ConvertVector") {
            materialPath {
                moveTo(2F, 3F)
                verticalLineTo(9F)
                horizontalLineTo(4.95F)
                lineTo(6.95F, 15F)
                horizontalLineTo(6F)
                verticalLineTo(21F)
                horizontalLineTo(12F)
                verticalLineTo(16.41F)
                lineTo(17.41F, 11F)
                horizontalLineTo(22F)
                verticalLineTo(5F)
                horizontalLineTo(16F)
                verticalLineTo(9.57F)
                lineTo(10.59F, 15F)
                horizontalLineTo(9.06F)
                lineTo(7.06F, 9F)
                horizontalLineTo(8F)
                verticalLineTo(3F)
                moveTo(4F, 5F)
                horizontalLineTo(6F)
                verticalLineTo(7F)
                horizontalLineTo(4F)
                moveTo(18F, 7F)
                horizontalLineTo(20F)
                verticalLineTo(9F)
                horizontalLineTo(18F)
                moveTo(8F, 17F)
                horizontalLineTo(10F)
                verticalLineTo(19F)
                horizontalLineTo(8F)
                close()
                moveTo(19F, 21F)
                verticalLineTo(19F)
                horizontalLineTo(15F)
                verticalLineTo(17F)
                horizontalLineTo(19F)
                verticalLineTo(15F)
                lineTo(22F, 18F)
                lineTo(19F, 21F)
            }
        }

    val DestinationDirectory =
        materialIcon("DestinationDirectory") {
            materialPath {
                moveTo(20F, 18F)
                horizontalLineTo(4F)
                verticalLineTo(8F)
                horizontalLineTo(20F)
                moveTo(20F, 6F)
                horizontalLineTo(12F)
                lineTo(10F, 4F)
                horizontalLineTo(4F)
                arcTo(2F, 2F, 0F, false, false, 2F, 6F)
                verticalLineTo(18F)
                arcTo(2F, 2F, 0F, false, false, 4F, 20F)
                horizontalLineTo(20F)
                arcTo(2F, 2F, 0F, false, false, 22F, 18F)
                verticalLineTo(8F)
                arcTo(2F, 2F, 0F, false, false, 20F, 6F)
                moveTo(14F, 9F)
                horizontalLineTo(16F)
                verticalLineTo(13F)
                horizontalLineTo(19F)
                lineTo(15F, 17F)
                lineTo(11F, 13F)
                horizontalLineTo(14F)
                close()
            }
        }

    val ErrorCircle =
        materialIcon("ErrorCircle") {
            materialPath {
                moveTo(11F, 15F)
                horizontalLineTo(13F)
                verticalLineTo(17F)
                horizontalLineTo(11F)
                verticalLineTo(15F)
                moveTo(11F, 7F)
                horizontalLineTo(13F)
                verticalLineTo(13F)
                horizontalLineTo(11F)
                verticalLineTo(7F)
                moveTo(12F, 2F)
                curveTo(6.47F, 2F, 2F, 6.5F, 2F, 12F)
                arcTo(10F, 10F, 0F, false, false, 22F, 12F)
                arcTo(10F, 10F, 0F, false, false, 12F, 2F)
                moveTo(12F, 20F)
                arcTo(8F, 8F, 0F, false, true, 4F, 12F)
                arcTo(8F, 8F, 0F, false, true, 12F, 20F)
                close()
            }
        }

    val ExploreFiles =
        materialIcon("ExploreFiles") {
            materialPath {
                moveTo(4F, 4F)
                curveTo(2.89F, 4F, 2F, 4.89F, 2F, 6F)
                verticalLineTo(18F)
                arcTo(2F, 2F, 0F, false, false, 4F, 20F)
                horizontalLineTo(20F)
                arcTo(2F, 2F, 0F, false, false, 22F, 18F)
                verticalLineTo(8F)
                curveTo(22F, 6.89F, 21.1F, 6F, 20F, 6F)
                horizontalLineTo(12F)
                lineTo(10F, 4F)
                horizontalLineTo(4F)
                moveTo(4F, 8F)
                horizontalLineTo(20F)
                verticalLineTo(18F)
                horizontalLineTo(4F)
                verticalLineTo(8F)
                moveTo(7F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(9F)
                verticalLineTo(22F)
                horizontalLineTo(7F)
                moveTo(11F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(13F)
                verticalLineTo(22F)
                horizontalLineTo(11F)
                moveTo(15F, 22F)
                verticalLineTo(24F)
                horizontalLineTo(17F)
                verticalLineTo(22F)
                horizontalLineTo(15F)
            }
        }

    val SourceFiles =
        materialIcon("SourceFiles") {
            materialPath {
                // M12,12L16,16H13.5V19H10.5V16H8L12,12Z
                moveTo(16F, 0F)
                horizontalLineTo(8F)
                curveTo(6.9F, 0F, 6F, .9F, 6F, 2F)
                verticalLineTo(18F)
                curveTo(6F, 19.1F, 6.9F, 20F, 8F, 20F)
                horizontalLineTo(20F)
                curveTo(21.1F, 20F, 22F, 19.1F, 22F, 18F)
                verticalLineTo(6F)
                lineTo(16F, 0F)
                moveTo(20F, 18F)
                horizontalLineTo(8F)
                verticalLineTo(2F)
                horizontalLineTo(15F)
                verticalLineTo(7F)
                horizontalLineTo(20F)
                verticalLineTo(18F)
                moveTo(4F, 4F)
                verticalLineTo(22F)
                horizontalLineTo(20F)
                verticalLineTo(24F)
                horizontalLineTo(4F)
                curveTo(2.9F, 24F, 2F, 23.1F, 2F, 22F)
                verticalLineTo(4F)
                horizontalLineTo(4F)
                close()
                moveTo(14F, 8F)
                lineTo(18F, 12F)
                horizontalLineTo(15F)
                verticalLineTo(16F)
                horizontalLineTo(13F)
                verticalLineTo(12F)
                horizontalLineTo(10F)
                lineTo(14F, 8F)
                close()
            }
        }

    val ToggleTheme =
        materialIcon("ToggleTheme") {
            materialPath {
                moveTo(7.5F, 2F)
                curveTo(5.71F, 3.15F, 4.5F, 5.18F, 4.5F, 7.5F)
                curveTo(4.5F, 9.82F, 5.71F, 11.85F, 7.53F, 13F)
                curveTo(4.46F, 13F, 2F, 10.54F, 2F, 7.5F)
                arcTo(5.5F, 5.5F, 0F, false, true, 7.5F, 2F)
                moveTo(19.07F, 3.5F)
                lineTo(20.5F, 4.93F)
                lineTo(4.93F, 20.5F)
                lineTo(3.5F, 19.07F)
                lineTo(19.07F, 3.5F)
                moveTo(12.89F, 5.93F)
                lineTo(11.41F, 5F)
                lineTo(9.97F, 6F)
                lineTo(10.39F, 4.3F)
                lineTo(9F, 3.24F)
                lineTo(10.75F, 3.12F)
                lineTo(11.33F, 1.47F)
                lineTo(12F, 3.1F)
                lineTo(13.73F, 3.13F)
                lineTo(12.38F, 4.26F)
                lineTo(12.89F, 5.93F)
                moveTo(9.59F, 9.54F)
                lineTo(8.43F, 8.81F)
                lineTo(7.31F, 9.59F)
                lineTo(7.65F, 8.27F)
                lineTo(6.56F, 7.44F)
                lineTo(7.92F, 7.35F)
                lineTo(8.37F, 6.06F)
                lineTo(8.88F, 7.33F)
                lineTo(10.24F, 7.36F)
                lineTo(9.19F, 8.23F)
                lineTo(9.59F, 9.54F)
                moveTo(19F, 13.5F)
                arcTo(5.5F, 5.5F, 0F, false, true, 13.5F, 19F)
                curveTo(12.28F, 19F, 11.15F, 18.6F, 10.24F, 17.93F)
                lineTo(17.93F, 10.24F)
                curveTo(18.6F, 11.15F, 19F, 12.28F, 19F, 13.5F)
                moveTo(14.6F, 20.08F)
                lineTo(17.37F, 18.93F)
                lineTo(17.13F, 22.28F)
                lineTo(14.6F, 20.08F)
                moveTo(18.93F, 17.38F)
                lineTo(20.08F, 14.61F)
                lineTo(22.28F, 17.15F)
                lineTo(18.93F, 17.38F)
                moveTo(20.08F, 12.42F)
                lineTo(18.94F, 9.64F)
                lineTo(22.28F, 9.88F)
                lineTo(20.08F, 12.42F)
                moveTo(9.63F, 18.93F)
                lineTo(12.4F, 20.08F)
                lineTo(9.87F, 22.27F)
                lineTo(9.63F, 18.93F)
                close()
            }
        }
}
